import fs from "fs/promises";
import path from "path";

// Tailwind's content scanner (tailwind.config.js) only reads real files —
// ./app/**/*.{js,jsx} and ./components/**/*.{js,jsx} — so it never sees
// class names used only inside an admin-authored template's `code` string,
// which lives in MongoDB and is compiled at runtime (see
// lib/compileTemplateCode.js). A class that isn't already used verbatim
// somewhere in the static codebase gets no CSS rule at all, and silently
// renders unstyled.
//
// This file's job is narrow: given every template's raw code, write it
// into a file Tailwind's scanner *does* see, purely as inert text — no one
// ever imports or executes it. Two callers regenerate it: the admin
// template write routes (app/api/admin/templates/**), so `next dev` picks
// up new classes live as an admin saves, and scripts/generateTemplateClassScan.mjs,
// run before every production build (see package.json's predev/prebuild),
// since production CSS is generated once at `next build` and never rescanned
// afterward.
//
// Deliberately at the project root in its own directory, *not* under
// app/ or components/ (added to tailwind.config.js's `content` as its own
// entry) — writing here from an API route while `next dev` is running once
// corrupted that same request's response, because Next's dev server treats
// any change under app/**|components/** as a page/component module-graph
// event and can tear down in-flight work reacting to it, even though
// nothing actually imports this file.
export const TEMPLATE_CLASS_SCAN_PATH = path.join(process.cwd(), ".tailwind-scan/templates.jsx");

export async function writeTemplateClassScan(codeStrings) {
  const body = codeStrings
    .filter((code) => typeof code === "string" && code)
    .map((code) => JSON.stringify(code))
    .join(",\n  ");

  const contents = `// AUTO-GENERATED by lib/templateClassScan.js — do not edit by hand.
// Exists only so Tailwind's content scanner (tailwind.config.js) can see
// class names used inside admin-authored (DB-stored) template code, which
// otherwise lives outside every file Tailwind scans. Never imported or
// executed anywhere — mirrors raw template source as inert text.
export const _TEMPLATE_CLASS_SCAN_SOURCE = [
  ${body}
];
`;

  await fs.mkdir(path.dirname(TEMPLATE_CLASS_SCAN_PATH), { recursive: true });
  await fs.writeFile(TEMPLATE_CLASS_SCAN_PATH, contents, "utf8");
}
